### PR TITLE
Multiple small bugfixes

### PR DESCRIPTION
**Pull request by Aciho**
Mostly just typos, but there were a couple of places I had to guess at the original intent. I also reformatted the file to make it more readable, hoping that github would ignore the whitespace changes cleanly, but it doesn't seem to have worked out, so sorry about that. Let me know if you want just the fixes without the reformat and I'll see what I can do.

### CODE REVIEW

**Comment by sum1won** [comment]
Yeah, the whitespace thing is a pain.

**Comment by Aciho** [comment]
OK, let's see what I can do about it

**Comment by sum1won** [comment]
Oh, I don't mean that it needs fixing.  I was just commiserating, since I've made the same effort.

**Comment by Aciho** [comment]
Well, I have a version without it, so at least you can see the changes I've made without whitespace nonsense blotting everything out.

**Pull request closed without merging**
